apiVersion: v1
kind: Service
metadata:
  name: {{ include "mcp-hangar-operator.fullname" . }}-metrics
  labels:
    {{- include "mcp-hangar-operator.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.operator.metrics.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "mcp-hangar-operator.selectorLabels" . | nindent 4 }}
